#!/bin/bash
export COMPOSER_PROVIDERS='{"github": {"provider": "github","module": "passport-github","clientID": "d580d961ba678e994bc4","clientSecret": "49a3cdc56502d562f16eb43ca442806a29c72622","authPath": "/auth/github","callbackURL": "/auth/github/callback","successRedirect": "http://localhost:5500/","failureRedirect": "/"}}'
composer-rest-server -c admin@seculab-network -n never -u true -w true -m true
